# Generated by Django 4.0.2 on 2022-02-08 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_remove_course_contact_contact_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='branch',
        ),
        migrations.AddField(
            model_name='branch',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='courses.course'),
        ),
    ]
