# Generated by Django 4.0.2 on 2022-02-10 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='latitude',
            field=models.CharField(default='00,00', max_length=50),
        ),
        migrations.AlterField(
            model_name='branch',
            name='longtitude',
            field=models.CharField(default='00,00', max_length=50),
        ),
    ]
