# Generated by Django 4.0.2 on 2022-02-09 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_course_branch_branch_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='address', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='category',
            name='imgpath',
            field=models.CharField(default='imgpath', max_length=20),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='Not choosen', max_length=50),
        ),
    ]
