# Generated by Django 4.0.2 on 2022-02-10 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_branch_latitude_alter_branch_longtitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='type',
        ),
    ]
