# Generated by Django 4.0.2 on 2022-02-10 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_remove_contact_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='type',
            field=models.CharField(choices=[('1', 'Phone'), ('2', 'Facebook'), ('3', 'E-mail')], default=1, max_length=30),
            preserve_default=False,
        ),
    ]
