# Generated by Django 4.0.2 on 2022-02-10 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_contact_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='type',
        ),
    ]
